fix compile issue if clang is used as host compiler for CUDA (#651)
Fix compile issues like:

```
ComputeApi.hpp(62): error #20093-D: address of a __shared__ variable "shMem" cannot be directly taken in a host function
286
19:54:35
              return reinterpret_cast<T*>(shMem);
```

```
api/util.hpp:66:8: error: no matching function for call to 'adjustToLimit'
   66 | return detail::adjustToLimit< T_limit, T_index, T_increment> (input, std::make_index_sequence< std::template decay< __decltype(input)> ::type::dim()> {});
```